### ISSUE TITLE
jquery的按钮点击高亮和tabbar和可以换图标 图片背景封装无所谓

### ISSUE THREAD

**Issue by sounddoor** [iinterest/Squirrel-3#29]
jquery的按钮点击高亮和tabbar和可以换图标 图片背景封装无所谓

**Comment by iinterest** [comment]
不太确定你说的是哪一部分，能更具体点吗？

**Comment by sounddoor** [comment]
1. 就是按钮点击没有高亮效果，是我自己写的。
2. 底部的按钮不能自定义图片，就是类似微信底部的微信 通讯录 发现 我这个

**Comment by iinterest** [comment]
感谢反馈，
1. 按钮高亮会在下个版本统一加上；
2. 底部 icon 用的是字体 icon，所以没有考虑图片，这个会进行兼容

**Comment by dev-chain247** [comment]
# [Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

 We're hiring for position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 19, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
jterrazz, @jonas-meng, @smartdapan, @GoodnessEzeokafor, @xtools-at, @KirubaKiruba, @fuckgm, @trungthaihieu93-dev, @rollfiend, @NORARK, @iolson, @dwojcik92, @Mcculloughj, @zoneboy, @nonafiona, @Ethanshanyu, @anyinfa, @fortrue, @Dilrong, @jundayw
